# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)
dry_fruits = DryFruit.create(
[
  { :name => 'Apricot', :scientificname => 'Prunus armeniaca', :energy => 241, :fat => 0.5, :protein => 3.4, :imagesmall => 'apricot.jpg', :imagelarge1 => 'apricot1.jpg', :imagelarge2 => 'apricot2.jpg', :imagelarge3 => 'apricot3.jpg', :vitamin_a => 0, :vitamin_b1 => 0, :vitamin_b2 => 0, :vitamin_b3 => 0, :vitamin_b5 => 0, :vitamin_b6 => 0, :vitamin_b9 => 0, :vitamin_b12 => 0, :vitamin_c => 1, :vitamin_d => 0, :vitamin_e => 0, :vitamin_k => 0, :carbohydrates => 0, :calcium => 0, :iron => 2.7, :magnesium => 0, :manganese => 0, :phosphorus => 0, :potassium => 0, :sodium => 0, :zinc => 0, :about => 'The apricot is a small tree, 8-12 m (26-39 ft) tall, with a trunk up to 40 cm (16 in) in diameter and a dense, spreading canopy. The leaves are ovate, 5-9 cm (2.0-3.5 in) long and 4-8 cm (1.6-3.1 in) wide, with a rounded base, a pointed tip and a finely serrated margin.', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Almond', :scientificname => 'Prunus dulcis', :energy => 576, :fat => 49.42, :protein => 21.22, :imagesmall => 'almond.jpg', :imagelarge1 => 'almond1.jpg', :imagelarge2 => 'almond2.jpg', :imagelarge3 => 'almond3.jpg', :vitamin_a => 0, :vitamin_b1 => 0.211, :vitamin_b2 => 1.014, :vitamin_b3 => 3.385, :vitamin_b5 => 0.469, :vitamin_b6 => 0.143, :vitamin_b9 => 50, :vitamin_b12 => 0, :vitamin_c => 0, :vitamin_d => 0, :vitamin_e => 26.2, :vitamin_k => 0, :carbohydrates => 21.7, :calcium => 264, :iron => 3.72, :magnesium => 268, :manganese => 2.285, :phosphorus => 484, :potassium => 705, :sodium => 5, :zinc => 3.08, :about => 'The almond is a species of tree native to the Middle East and South Asia. "Almond" is also the name of the edible and widely cultivated seed of this tree.', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Cashew', :scientificname => 'Anacardium occidentale', :energy => 553, :fat => 43.85, :protein => 18.22, :imagesmall => 'cashew.jpg', :imagelarge1 => 'cashew1.jpg', :imagelarge2 => 'cashew2.png', :imagelarge3 => 'cashew3.jpg', :vitamin_a => 0, :vitamin_b1 => 0.42, :vitamin_b2 => 0.06, :vitamin_b3 => 1.06, :vitamin_b5 => 0.86, :vitamin_b6 => 0.42, :vitamin_b9 => 25, :vitamin_b12 => 0, :vitamin_c => 0.5, :vitamin_d => 0, :vitamin_e => 0.9, :vitamin_k => 0, :carbohydrates => 30.19, :calcium => 37, :iron => 6.68, :magnesium => 292, :manganese => 1.66, :phosphorus => 593, :potassium => 660, :sodium => 12, :zinc => 5.78, :about => 'The cashew is a tree in the family Anacardiaceae. Its English name derives from the Portuguese name for the fruit of the cashew tree, caju, which in turn derives from the indigenous Tupi name, acaju. Originally native to Northeast Brazil, it is now widely grown in tropical climates for its cashew seeds and cashew apples.', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Dates', :scientificname => 'Phoenix dactylifera', :energy => 282, :fat => 0.39, :protein => 2.45, :imagesmall => 'dates.jpg', :imagelarge1 => 'dates1.jpg', :imagelarge2 => 'dates2.jpg', :imagelarge3 => 'dates3.jpg', :vitamin_a => 10, :vitamin_b1 => 0.052, :vitamin_b2 => 0.066, :vitamin_b3 => 1.274, :vitamin_b5 => 0.589, :vitamin_b6 => 0.165, :vitamin_b9 => 19, :vitamin_b12 => 0, :vitamin_c => 0.4, :vitamin_d => 0, :vitamin_e => 0.05, :vitamin_k => 2.7, :carbohydrates => 75.03, :calcium => 39, :iron => 1.02, :magnesium => 43, :manganese => 0.262, :phosphorus => 62, :potassium => 656, :sodium => 2, :zinc => 0.29, :about => 'Dates have been a staple food of the Middle East and parts of South Asia for thousands of years. They are believed to have originated around Iraq, and have been cultivated since ancient times from Mesopotamia to prehistoric Egypt, possibly as early as 4000 BCE. The Ancient Egyptians used the fruits to be made into date wine, and ate them at harvest. There is archaeological evidence of date cultivation in eastern Arabia in 6000 BCE', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Pistachio', :scientificname => 'Pistacia vera', :energy => 571, :fat => 45.97, :protein => 21.35, :imagesmall => 'pista.png', :imagelarge1 => 'pista1.png', :imagelarge2 => 'pista2.jpg', :imagelarge3 => 'pista3.jpg', :vitamin_a => 0, :vitamin_b1 => 0.84, :vitamin_b2 => 0.158, :vitamin_b3 => 1.425, :vitamin_b5 => 0.513, :vitamin_b6 => 1.274, :vitamin_b9 => 50, :vitamin_b12 => 0, :vitamin_c => 2.3, :vitamin_d => 0, :vitamin_e => 0, :vitamin_k => 0, :carbohydrates => 27.65, :calcium => 110, :iron => 4.2, :magnesium => 120, :manganese => 1.275, :phosphorus => 485, :potassium => 1042, :sodium => 0, :zinc => 2.3, :about => 'The pistachio is a small tree originally from Greater Iran (Iran and Iraq[1][2]) which now can also be found in regions of Syria, Lebanon, Turkey, Greece, Tunisia, Kyrgyzstan, Tajikistan, Turkmenistan, India, Pakistan, Egypt, Italy (Sicily), Uzbekistan, Afghanistan (especially in the provinces of Samangan and Badghis), and the United States, specifically in California. The tree produces an important culinary nut.', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Walnut', :scientificname => 'Juglans regia', :energy => 654, :fat => 65.21, :protein => 15.23, :imagesmall => 'walnut.jpg', :imagelarge1 => 'walnut1.jpg', :imagelarge2 => 'walnut2.jpg', :imagelarge3 => 'walnut3.jpg', :vitamin_a => 20, :vitamin_b1 => 0.341, :vitamin_b2 => 0.15, :vitamin_b3 => 1.125, :vitamin_b5 => 0.570, :vitamin_b6 => 0.537, :vitamin_b9 => 98, :vitamin_b12 => 0, :vitamin_c => 1.3, :vitamin_d => 0, :vitamin_e => 0.7, :vitamin_k => 2.7, :carbohydrates => 13.71, :calcium => 98, :iron => 2.91, :magnesium => 158, :manganese => 3.414, :phosphorus => 346, :potassium => 441, :sodium => 2, :zinc => 3.09, :about => 'Walnuts are rounded, single-seeded stone fruits of the walnut tree. The walnut fruit is enclosed in a green, leathery, fleshy husk. This husk is inedible. After harvest, the removal of the husk reveals the wrinkly walnut shell, which is in two halves. This shell is hard and encloses the kernel, which is also made up of two halves separated by a partition. The seed kernels - commonly available as shelled walnuts - are enclosed in a brown seed coat which contains antioxidants. The antioxidants protect the oil-rich seed from atmospheric oxygen so preventing rancidity.', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Raisin', :scientificname => 'Dried Grapes', :energy => 299, :fat => 0.5, :protein => 3, :imagesmall => 'raisin.jpg', :imagelarge1 => 'raisin1.jpg', :imagelarge2 => 'raisin2.jpg', :imagelarge3 => 'raisin3.jpg', :vitamin_a => 0, :vitamin_b1 => 0, :vitamin_b2 => 0, :vitamin_b3 => 0, :vitamin_b5 => 0, :vitamin_b6 => 0, :vitamin_b9 => 0, :vitamin_b12 => 0, :vitamin_c => 0, :vitamin_d => 0, :vitamin_e => 0, :vitamin_k => 0, :carbohydrates => 79, :calcium => 50, :iron => 1.9, :magnesium => 0, :manganese => 0, :phosphorus => 0, :potassium => 750, :sodium => 11, :zinc => 0, :about => 'A raisin is a dried grape. Raisins are produced in many regions of the world and may be eaten raw or used in cooking, baking and brewing. In the United Kingdom, Ireland, New Zealand, Australia, and Canada the word "raisin" is reserved for the dark-coloured dried large grape, with "sultana" being a golden-coloured dried grape, and "currant" being a dried small Black Corinth grape', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Prunes', :scientificname => 'Prunus domestica', :energy => 240, :fat => 0.38, :protein => 2.18, :imagesmall => 'prunes.jpg', :imagelarge1 => 'prunes1.jpg', :imagelarge2 => 'prunes2.jpg', :imagelarge3 => 'prunes3.jpg', :vitamin_a => 781, :vitamin_b1 => 0, :vitamin_b2 => 0, :vitamin_b3 => 0, :vitamin_b5 => 0, :vitamin_b6 => 0, :vitamin_b9 => 0, :vitamin_b12 => 0, :vitamin_c => 0.6, :vitamin_d => 0, :vitamin_e => 0, :vitamin_k => 0, :carbohydrates => 63.88, :calcium => 0, :iron => 0, :magnesium => 0, :manganese => 0, :phosphorus => 69, :potassium => 732, :sodium => 0, :zinc => 0, :about => 'A prune is any of various plum cultivars, mostly Prunus domestica or European Plum, sold as fresh or dried fruit. The dried fruit is also referred to as a dried plum. In general, fresh prunes are freestone cultivars (the pit is easy to remove), whereas most other plums grown for fresh consumption are clingstone (the pit is more difficult to remove).', :benefits => '', :sideeffects => '', :extra => '' },
  { :name => 'Figs', :scientificname => 'Ficus carica', :energy => 249, :fat => 0.93, :protein => 3.3, :imagesmall => 'figs.jpg', :imagelarge1 => 'figs1.jpg', :imagelarge2 => 'figs2.jpg', :imagelarge3 => 'figs3.jpg', :vitamin_a => 0, :vitamin_b1 => 0.085, :vitamin_b2 => 0.082, :vitamin_b3 => 0.619, :vitamin_b5 => 0.434, :vitamin_b6 => 0.106, :vitamin_b9 => 9, :vitamin_b12 => 0, :vitamin_c => 1.2, :vitamin_d => 0, :vitamin_e => 0, :vitamin_k => 0, :carbohydrates => 63.87, :calcium => 162, :iron => 2.03, :magnesium => 68, :manganese => 0, :phosphorus => 67, :potassium => 680, :sodium => 0, :zinc => 0.55, :about => 'The edible fruit consists of the mature syconium containing numerous one-seeded fruits (druplets). The fruit is 3-5 centimetres (1.2-2.0 in) long, with a green skin, sometimes ripening towards purple or brown. Ficus carica has milky sap (laticifer). The sap of the figs green parts is an irritant to human skin.', :benefits => '', :sideeffects => '', :extra => '' },
])
  
users = User.create(
[
  { :email => 'abhimanyu@netjoos.com', :firstname => 'Abhimanyu', :lastname => 'Sirohi', :passwordhash => '', :dob => DateTime.new(1980, 6, 28), :height => 178, :weight => 88, :picture => 'abhi.jpg', :role => 0 }
]
)

bowls = Bowl.create(
[
  { :userid => 1, :name => 'MyBowl 1', :colour => '#f0f0f0', :created => DateTime.new(2012, 12, 9), :modified => DateTime.new(2012, 12, 9) }
]
)

contents = Content.create(
[
  { :bowlid => 1, :dryfruitid => 1, :quantity => 10 },
  { :bowlid => 1, :dryfruitid => 2, :quantity => 5 }
]
)
